#!/usr/bin/env bash
# Install Forge + ComfyUI under vendors/ for Apple Silicon (macOS arm64).
# Idempotent: safe to re-run. Does not download checkpoints.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENDORS="${ROOT}/vendors"
FORGE_DIR="${VENDORS}/stable-diffusion-webui-forge"
COMFY_DIR="${VENDORS}/ComfyUI"
SHARED_CKPT="${VENDORS}/models/checkpoints"
FORGE_REPO="https://github.com/lllyasviel/stable-diffusion-webui-forge.git"
COMFY_REPO="https://github.com/comfyanonymous/ComfyUI.git"

die() {
  echo "error: $*" >&2
  exit 1
}

require_apple_silicon() {
  local os arch
  os="$(uname -s)"
  arch="$(uname -m)"
  if [[ "${os}" != "Darwin" || "${arch}" != "arm64" ]]; then
    die "install:backends supports Apple Silicon (darwin/arm64) only (got ${os}/${arch})."
  fi
}

pick_python() {
  local candidate
  for candidate in python3.12 python3.11 python3.10 python3; do
    if command -v "${candidate}" >/dev/null 2>&1; then
      local ver
      ver="$("${candidate}" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
      # Prefer 3.10–3.12 for Forge/torch compatibility; allow 3.13+ with a warning.
      if [[ "${ver}" == "3.10" || "${ver}" == "3.11" || "${ver}" == "3.12" ]]; then
        echo "${candidate}"
        return 0
      fi
    fi
  done
  # Fall back to python3 if version is ≥3.10
  if command -v python3 >/dev/null 2>&1; then
    local major minor
    major="$(python3 -c 'import sys; print(sys.version_info.major)')"
    minor="$(python3 -c 'import sys; print(sys.version_info.minor)')"
    if [[ "${major}" -eq 3 && "${minor}" -ge 10 ]]; then
      if [[ "${minor}" -ge 13 ]]; then
        echo "warning: using python3 ${major}.${minor}; Forge/ComfyUI are better tested on 3.10–3.12. Install python@3.12 via Homebrew if install fails." >&2
      fi
      echo "python3"
      return 0
    fi
  fi
  die "need Python ≥3.10 (prefer 3.12). Try: brew install python@3.12"
}

clone_or_update() {
  local url="$1"
  local dest="$2"
  if [[ -d "${dest}/.git" ]]; then
    echo "→ updating $(basename "${dest}")"
    git -C "${dest}" pull --ff-only || echo "warning: git pull failed for ${dest}; continuing with existing clone" >&2
  else
    echo "→ cloning $(basename "${dest}")"
    mkdir -p "$(dirname "${dest}")"
    git clone --depth 1 "${url}" "${dest}"
  fi
}

ensure_shared_checkpoints() {
  mkdir -p "${SHARED_CKPT}"
  # Keep an empty placeholder so the dir exists after clone without models.
  if [[ ! -f "${SHARED_CKPT}/.gitkeep" ]]; then
    touch "${SHARED_CKPT}/.gitkeep"
  fi
}

link_checkpoint_dir() {
  local target="$1"
  local parent
  parent="$(dirname "${target}")"
  mkdir -p "${parent}"
  if [[ -L "${target}" ]]; then
    local current
    current="$(readlink "${target}")"
    if [[ "${current}" == "${SHARED_CKPT}" ]]; then
      return 0
    fi
    rm -f "${target}"
  elif [[ -d "${target}" ]]; then
    # Preserve any existing local checkpoints into the shared dir, then replace.
    if [[ -n "$(ls -A "${target}" 2>/dev/null || true)" ]]; then
      echo "→ moving existing checkpoints from ${target} into shared dir"
      # shellcheck disable=SC2086
      mv "${target}"/* "${SHARED_CKPT}/" 2>/dev/null || true
    fi
    rm -rf "${target}"
  fi
  ln -sfn "${SHARED_CKPT}" "${target}"
  echo "→ linked ${target} → ${SHARED_CKPT}"
}

setup_forge() {
  local py="$1"
  clone_or_update "${FORGE_REPO}" "${FORGE_DIR}"

  # Apple Silicon + API launch args (COMMANDLINE_ARGS consumed by webui.sh).
  cat > "${FORGE_DIR}/webui-user.sh" <<'EOF'
#!/usr/bin/env bash
# Generated by llm_playground scripts/install-image-backends.sh — Apple Silicon.
export PYTORCH_ENABLE_MPS_FALLBACK=1
export COMMANDLINE_ARGS="--api --listen --port 7860 --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate --no-half --no-download-sd-model"
EOF
  chmod +x "${FORGE_DIR}/webui-user.sh"

  if [[ ! -d "${FORGE_DIR}/venv" ]]; then
    echo "→ creating Forge venv with ${py}"
    "${py}" -m venv "${FORGE_DIR}/venv"
  fi

  # shellcheck disable=SC1091
  source "${FORGE_DIR}/venv/bin/activate"
  # setuptools≥82 dropped pkg_resources; openai/CLIP still imports it at build time.
  # Use --no-build-isolation so the venv's setuptools is used (isolated builds pull latest).
  python -m pip install --upgrade pip wheel
  python -m pip install "setuptools==69.5.1"
  # MPS-capable torch from the default PyPI wheels (macOS arm64).
  python -m pip install --upgrade torch torchvision
  # Forge / older skimage break on NumPy 2.
  python -m pip install "numpy<2"
  # Pre-install CLIP so webui.sh does not fail the first cold start on Mac.
  python -m pip install --no-build-isolation \
    "https://github.com/openai/CLIP/archive/d50d76daa670286dd6cacf3bcd80b5e4823fc8e1.zip" || \
    echo "warning: CLIP pre-install failed; Forge first start may retry." >&2
  # Let Forge's own installer finish remaining deps on first start if needed;
  # pull the common requirements if present for AC-3 (deps installed at install time).
  if [[ -f "${FORGE_DIR}/requirements_versions.txt" ]]; then
    python -m pip install --no-build-isolation -r "${FORGE_DIR}/requirements_versions.txt" || \
      echo "warning: Forge requirements_versions.txt had install errors; first webui start may finish setup." >&2
  elif [[ -f "${FORGE_DIR}/requirements.txt" ]]; then
    python -m pip install --no-build-isolation -r "${FORGE_DIR}/requirements.txt" || \
      echo "warning: Forge requirements.txt had install errors; first webui start may finish setup." >&2
  fi
  # Re-pin after requirements in case a dep pulled NumPy 2 / incompatible OpenCV.
  python -m pip install "numpy==1.26.2"
  python -m pip install "opencv-python-headless==4.8.1.78" 2>/dev/null || \
    python -m pip install "opencv-python==4.8.1.78" 2>/dev/null || true
  deactivate || true

  mkdir -p "${FORGE_DIR}/models"
  link_checkpoint_dir "${FORGE_DIR}/models/Stable-diffusion"
}

setup_comfy() {
  local py="$1"
  clone_or_update "${COMFY_REPO}" "${COMFY_DIR}"

  if [[ ! -d "${COMFY_DIR}/venv" ]]; then
    echo "→ creating ComfyUI venv with ${py}"
    "${py}" -m venv "${COMFY_DIR}/venv"
  fi

  # shellcheck disable=SC1091
  source "${COMFY_DIR}/venv/bin/activate"
  python -m pip install --upgrade pip wheel setuptools
  python -m pip install --upgrade torch torchvision torchaudio
  if [[ -f "${COMFY_DIR}/requirements.txt" ]]; then
    python -m pip install -r "${COMFY_DIR}/requirements.txt"
  fi
  deactivate || true

  mkdir -p "${COMFY_DIR}/models"
  link_checkpoint_dir "${COMFY_DIR}/models/checkpoints"
}

main() {
  require_apple_silicon
  command -v git >/dev/null 2>&1 || die "git is required"
  local py
  py="$(pick_python)"
  echo "Using Python: $(command -v "${py}") ($("${py}" --version 2>&1))"

  mkdir -p "${VENDORS}/logs" "${VENDORS}/models"
  ensure_shared_checkpoints
  setup_forge "${py}"
  setup_comfy "${py}"

  echo
  echo "Image backends installed under ${VENDORS}"
  echo "Drop open-weight checkpoints (.safetensors / .ckpt) into:"
  echo "  ${SHARED_CKPT}"
  echo "Then start with: npm run backends:start   or   npm run dev:all"
}

main "$@"
